import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideNav from "@/components/SideNav";
import Image from "next/image";
import { Cog6ToothIcon } from "@heroicons/react/16/solid";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navigation = [
  { name: "Home", href: "/", icon: <Cog6ToothIcon className="w-3" /> },
  {
    name: "Shift Summary",
    href: "/settings",
    icon: <Image src="/assets/logo.png" alt="more" width={16} height={16} />,
  },
];
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full bg-[#fff]">
      <body className="h-full  font-[poppins]">
        <div className="flex">
          {/* Static sidebar for desktop */}
          <div className="flex fixed flex-col">
            <div className="flex grow flex-col p-2 gap-y-6 bg-[#fff] border-r-[1px]  border-[#00000032]  min-h-screen h-full">
              <div className="flex justify-end mt-3">
                <Image
                  src="/assets/fast-forward.png"
                  alt="expand"
                  width={14}
                  height={14}
                  className="opacity-40"
                />
              </div>
              <a href="/" className="flex  items-center justify-center">
                <Image
                  className=""
                  src="/assets/logo.jpg"
                  width={65}
                  height={65}
                  alt="Your Company"
                />
              </a>
              <SideNav />
            </div>
          </div>

          <main className="ml-24 w-full h-full">
            <div className="w-full h-full">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
